services:
  # Servicio para tu aplicación
  app:
    build: .
    container_name: my_app_container
    environment:
      - DATABASE_URL=postgresql://library:library@db:5432/biblioteca
    depends_on:
      - db
    ports:
      - "8000:8000" # Exponiendo el puerto de la aplicación
    networks:
      - app_network

  # Servicio para PostgreSQL
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
      POSTGRES_DB: biblioteca
    ports:
      - "5442:5432" # Exponiendo el puerto 5442 al exterior
    volumes:
      - db_data:/var/lib/postgresql/data # Para persistir datos
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
